sudo: true
dist: trusty
addons:
os:
  - linux
apt:
  packages:
    - unoconv
    - libreoffice-dev
    - imagemagick
    - poppler-utils
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_script:
  - npm run lint
after_script:
  - npm run coveralls
git:
  depth: 10
cache:
  yarn: true
